# Generated by Django 5.2.7 on 2025-11-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'Utilizator', 'verbose_name_plural': 'Utilizatori'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_participant',
            field=models.BooleanField(default=True),
        ),
    ]
