# Generated by Django 5.2.7 on 2025-11-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_payment_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Eveniment', 'verbose_name_plural': 'Evenimente'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plată', 'verbose_name_plural': 'Plăți'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rezervare', 'verbose_name_plural': 'Rezervări'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['event', 'price'], 'verbose_name': 'Tip bilet', 'verbose_name_plural': 'Tipuri de bilete'},
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Text scurt afișat pe banner.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='promo_message',
            field=models.TextField(blank=True, help_text='Mesaj promoțional pentru pagină.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme_color',
            field=models.CharField(default='#4f46e5', help_text='Culoare temă pentru eveniment (hex, ex: #4f46e5).', max_length=20, validators=[django.core.validators.RegexValidator(message='Culoarea trebuie să fie un cod hex valid (ex: #4f46e5).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('completed', 'Finalizată'), ('failed', 'Eșuată')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
