# Generated by Django 6.0.1 on 2026-03-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_end_after_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
