# Generated by Django 6.0.1 on 2026-03-10 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_reservation_ticket_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['event', 'price'], 'verbose_name': 'Ticket type', 'verbose_name_plural': 'Ticket types'},
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Short banner text displayed on the event page.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='promo_message',
            field=models.TextField(blank=True, help_text='Promotional message displayed on the event page.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme_color',
            field=models.CharField(default='#4f46e5', help_text='Event theme color (hex format, example: #4f46e5).', max_length=20, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (example: #4f46e5).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
