# Generated by Django 6.0.1 on 2026-08-12 16:17

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(default=events.models.default_reservation_expiry, help_text='Unconfirmed reservations past this time can be released back to stock.'),
        ),
    ]
