# Generated by Django 6.0.2 on 2026-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_reservation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether this ticket has already been scanned/checked in at the event entrance.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
