# Generated by Django 6.0.1 on 2026-08-12 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_supportmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='thread_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Groups messages belonging to the same visitor/conversation.', verbose_name='Conversation thread'),
        ),
    ]
