# Generated by Django 5.1.7 on 2025-03-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenimente', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_available',
            field=models.IntegerField(default=0),
        ),
    ]
