# Generated by Django 5.1.7 on 2025-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenimente', '0005_review_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='decorations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='playlist',
            field=models.FileField(blank=True, null=True, upload_to='playlists/'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
